project_id = "awszwetvzugirgacpcem"

[functions.ai-reclassify-types]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.fix-transaction-types]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false
